name: nasser_core_package
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  image_picker: ^1.0.7
  injectable: ^2.1.0
  json_serializable: ^6.7.1
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  

dev_dependencies:
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # generate: true
  assets:
    - assets/langs/
    - assets/langs/ar.json
    - assets/langs/en.json
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
